import Head from "next/head";
import Image from "next/image";
import { HCFLayout } from "@/components/HCFLayout";
import { HeaderMenu } from "@/components/HeaderMenu";
import { Footer } from "@/components/Footer";
import { VerifierContainer } from "@/components/VerifierContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Open credential verifier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HCFLayout header={<HeaderMenu />} footer={<Footer />}>
        <main className={`grid place-content-center h-full p-4 md:p-8`}>
          <div className={`flex flex-col items-center gap-8 w-fit`}>
            <VerifierContainer />
            <div className={`flex flex-col items-center w-full gap-4`}>
              <p className={`text-lg font-bold text-lime-700`}>Supported by</p>
              <div
                className={`flex items-center justify-center gap-6 flex-wrap`}
              >
                <Image
                  src="/sakazuki_logo.png"
                  alt="sakazuki logo"
                  width={185}
                  height={32}
                />
                <Image
                  src="/vess_logo.png"
                  alt="vess logo"
                  width={123}
                  height={32}
                />
              </div>
            </div>
          </div>
        </main>
      </HCFLayout>
    </>
  );
}
