import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { DidkitRes, VerifyStatus } from "@/types";
import { verifyCredential } from "@spruceid/didkit-wasm";
import { useStatEerrorText, useStateVerifyStatus } from "@/lib/jotai";
import { HCFLayout } from "@/components/HCFLayout";
import { HeaderMenu } from "@/components/HeaderMenu";
import { Footer } from "@/components/Footer";
import { VerifierContainer } from "@/components/VerifierContainer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [vc, setVc] = useState("");
  const [res, setRes] = useStateVerifyStatus();
  const [error, setError] = useStatEerrorText();

  const verify = async (vc: string) => {
    try {
      setRes(VerifyStatus.verifying);
      const proofOptions = {};
      const res = await verifyCredential(vc, JSON.stringify(proofOptions));

      console.log({ res });

      const resJson = JSON.parse(res) as DidkitRes;
      // 検証失敗
      if (resJson.errors && resJson.errors.length > 0) {
        setError(resJson.errors.join(","));
        setRes(VerifyStatus.failed);
        return;
      }
      // 検証成功?
      if (resJson.warnings && resJson.warnings.length > 0) {
        setError(resJson.warnings.join(","));
        setRes(VerifyStatus.success);
        return;
      }

      //検証成功
      setError("");
      setRes(VerifyStatus.success);
    } catch (error) {
      console.error(error);
      setError(JSON.stringify(error));
      setRes(VerifyStatus.failed);
    }
  };

  const handleValidation = async () => {
    if (!vc) return;
    await verify(vc);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HCFLayout header={<HeaderMenu />} footer={<Footer />}>
        <main className={`grid place-content-center h-full p-4 md:p-8`}>
          <div className={`flex flex-col items-center gap-8 w-fit`}>
            <VerifierContainer />
            <div className={`flex flex-col items-center w-full gap-4`}>
              <p className={`text-lg font-bold text-lime-700`}>対応規格</p>
              <div
                className={`flex items-center justify-center gap-6 flex-wrap`}
              >
                <Image
                  src="/sakazuki_logo.png"
                  alt="sakazuki logo"
                  width={185}
                  height={32}
                />
                <Image
                  src="/vess_logo.png"
                  alt="vess logo"
                  width={123}
                  height={32}
                />
              </div>
            </div>
          </div>
        </main>
      </HCFLayout>
    </>
  );
}
