import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { DidkitRes, VerifyStatus } from "@/types";
import { verifyCredential } from "@spruceid/didkit-wasm";
import { useStatEerrorText, useStateVerifyStatus } from "@/lib/jotai";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [vc, setVc] = useState("");
  const [res, setRes] = useStateVerifyStatus();
  const [error, setError] = useStatEerrorText();

  const verify = async (vc: string) => {
    try {
      setRes(VerifyStatus.verifying);
      const proofOptions = {};
      const res = await verifyCredential(vc, JSON.stringify(proofOptions));

      console.log({ res });

      const resJson = JSON.parse(res) as DidkitRes;
      // 検証失敗
      if (resJson.errors && resJson.errors.length > 0) {
        setError(resJson.errors.join(","));
        setRes(VerifyStatus.failed);
        return;
      }
      // 検証成功?
      if (resJson.warnings && resJson.warnings.length > 0) {
        setError(resJson.warnings.join(","));
        setRes(VerifyStatus.success);
        return;
      }

      //検証成功
      setError("");
      setRes(VerifyStatus.success);
    } catch (error) {
      console.error(error);
      setError(JSON.stringify(error));
      setRes(VerifyStatus.failed);
    }
  };

  const handleValidation = async () => {
    if (!vc) return;
    await verify(vc);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <textarea
            className={`${styles.textarea}`}
            value={vc}
            onChange={(e) => setVc(e.target.value)}
            placeholder="テキストを入力してください"
          ></textarea>
          <br />
          <button onClick={handleValidation}>検証する</button>
          <div className={styles.center}>
            {res && res !== VerifyStatus.waiting && <p>{res}</p>}
            {error && error !== "" && <p>{error}</p>}
          </div>
        </div>
      </main>
    </>
  );
}
